In [1]:
pip install numpy

In [2]:
import numpy as np

In [25]:
a=np.array([1,2,3],dtype="int64")

In [20]:
print(a)

[1 2 3]


In [6]:
b=np.array([[9,8,7],[6,5,4]])

In [7]:
print(b)

[[9 8 7]
 [6 5 4]]


In [8]:
a.ndim

1

In [9]:
b.ndim

2

In [10]:
a.shape

(3,)

In [11]:
b.shape

(2, 3)

In [12]:
a.dtype
b.dtype

dtype('int64')

In [17]:
a.dtype

dtype('int32')

In [14]:
b.dtype

dtype('int64')

In [30]:
a.itemsize

8

In [31]:
b.itemsize

8

In [27]:
a.size

3

In [28]:
a.nbytes

24

In [29]:
a.size*a.itemsize

24

In [36]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [37]:
a.shape

(2, 7)

In [38]:
a[1,5]

13

In [39]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [40]:
a[:,2]

array([ 3, 10])

In [41]:
a[0,1:6:2]

array([2, 4, 6])

In [42]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [43]:
a[1,6]=20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 20]])

In [44]:
a[:,2]=[111,222]
a

array([[  1,   2, 111,   4,   5,   6,   7],
       [  8,   9, 222,  11,  12,  13,  20]])

In [45]:
a

array([[  1,   2, 111,   4,   5,   6,   7],
       [  8,   9, 222,  11,  12,  13,  20]])

In [46]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [47]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [48]:
b[0,1,1]

4

In [49]:
b[1,0,0]

5

In [50]:
b[:,1,:]=[9,9],[7,7]

In [51]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [7, 7]]])

In [54]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [57]:
np.zeros((2,3,4,3))

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [58]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [60]:
np.ones((2,3,4),dtype="int64")

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [61]:
np.full((3,3),123)

array([[123, 123, 123],
       [123, 123, 123],
       [123, 123, 123]])

In [62]:
np.full_like(a,5)

array([[5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5]])

In [63]:
np.full(a.shape,6)

array([[6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6]])

In [64]:
np.random.rand(2,3)

array([[0.84560439, 0.08236624, 0.20369577],
       [0.49180814, 0.5220124 , 0.24433891]])

In [65]:
np.random.rand(2,3,4)

array([[[0.64337697, 0.7574045 , 0.62654437, 0.90359894],
        [0.13450837, 0.58258313, 0.55982244, 0.46047494],
        [0.27457882, 0.0077596 , 0.95162128, 0.92688631]],

       [[0.5842956 , 0.84151189, 0.40270142, 0.2755829 ],
        [0.02423878, 0.01146139, 0.98190326, 0.97378023],
        [0.23162012, 0.22420938, 0.18629754, 0.71561713]]])

In [66]:
np.random.random_sample(a.shape)

array([[0.92421678, 0.92708534, 0.36400948, 0.16919706, 0.67814651,
        0.46772354, 0.87495493],
       [0.17850538, 0.18885349, 0.433648  , 0.67017785, 0.3544062 ,
        0.43577914, 0.71364656]])

In [74]:
np.random.randint(18,size=(2,4))

array([[12,  0,  4,  3],
       [ 2,  4,  1,  1]])

In [75]:
np.random.randint(10,18,size=(3,3))

array([[12, 14, 15],
       [17, 13, 11],
       [16, 16, 11]])

In [77]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [84]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [87]:
arr0=np.array([[1,2,3]])
r0=np.repeat(arr0,5,axis=0)
print(r0)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [85]:
arr1=np.array([1,2,3])
r2=np.repeat(arr1,2)
print(r2)

[1 1 2 2 3 3]


In [104]:
new=np.ones((5,5),dtype="int32")
new

new1=np.zeros((3,3))
print(new1)

new1[1,1]=9
print(new1)

new[1:4,1:4]=new1
print(new)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [124]:
a=np.array([1,2,3])
b=a.copy()
b[0]=12
print(b)

[12  2  3]


In [131]:
a=np.array([1,2,3])
b=a
b[0]=111
print(a)
print(b)

[111   2   3]
[111   2   3]


In [144]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [145]:
a+2

array([3, 4, 5, 6, 7])

In [134]:
a-2

array([-1,  0,  1,  2,  3])

In [135]:
a*2

array([ 2,  4,  6,  8, 10])

In [136]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [137]:
a//2

array([0, 1, 1, 2, 2])

In [138]:
a%2

array([1, 0, 1, 0, 1])

In [140]:
a +=2
a

array([5, 6, 7, 8, 9])

In [147]:
b=np.array([0,1,0,1,0])
a+b

array([1, 3, 3, 5, 5])

In [148]:
a**2 #power

array([ 1,  4,  9, 16, 25])

In [149]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [150]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

Linear algebra

In [153]:
a=np.ones((2,3))
print(a)

b=np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [155]:
c=np.identity(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [156]:
np.linalg.det(c)

1.0

In [162]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [163]:
np.min(stats)

1

In [172]:
np.min(stats,axis=0)

array([1, 2, 3])

In [173]:
np.min(stats,axis=1)

array([1, 4])

In [164]:
np.max(stats)

6

In [166]:
np.max(stats,axis=1)

array([3, 6])

In [167]:
np.max(stats,axis=0)

array([4, 5, 6])

In [174]:
np.sum(stats) #sum total value

21

In [171]:
np.sum(stats,axis=0) #sum column values

array([5, 7, 9])

In [175]:
np.sum(stats,axis=1) #sum row values


array([ 6, 15])

In [178]:
before=np.array([[1,2,3],[4,5,6]])
print(before)
print(before.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [184]:
after=before.reshape(3,2)
after

array([[1, 2],
       [3, 4],
       [5, 6]])

In [185]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

In [187]:
np.vstack([v1,v2,v1,v2]) #vertical stack

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [191]:
h1 = np.ones((2,4))
print(h1)
h2=np.zeros((2,2))
print(h2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


In [193]:
np.hstack((h1,h2))

array([[0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.]])